spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.93.96.60:3306/vhr
    username: root
    password: 888999
  redis:
    database: 0
    host: 47.93.96.60
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1ms
        min-idle: 0
  cache:
    cache-names: menu_cache
    redis:
      time-to-live: 1800s

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 8082
